using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Try_Catch
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //try
            //{
            //    int[] myNumbers = { 1, 2, 3 };
            //    Console.WriteLine(myNumbers[10]);
            //}
            //catch (Exception e)
            //{
            //    Console.WriteLine(e.Message);

            //    //You can also output your own error message:
            //    Console.WriteLine("Something went wrong.");
            //}

            ////The finally statement lets you execute code, after try...catch, regardless of the result:
            //finally 
            //{
            //    Console.WriteLine("The 'try catch' is finished.");
            //}  
            
            //Console.ReadKey();
        }
    }
}

//C# Exceptions:
///When executing C# code, different errors can occur: coding errors made by the programmer, errors due to wrong input, or other unforeseeable things.
///When an error occurs, C# will normally stop and generate an error message. The technical term for this is: C# will throw an exception (throw an error).

//C# try and catch:
///The try statement allows you to define a block of code to be tested for errors while it is being executed.
///The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
///The try and catch keywords come in pairs:
/// try
/// {
///     Block of code to try
/// }
/// catch (Exception e)
/// {
/// Block of code to handle errors
/// }





